# Generated by Django 4.1.2 on 2022-10-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jobpost_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='skills',
            new_name='skill',
        ),
    ]
