# Generated by Django 4.1.2 on 2022-10-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_subscribe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='option',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=10),
            preserve_default=False,
        ),
    ]
